version: "3.0"
services:
  e2e:
    build:
      context: .
      dockerfile: Dockerfile
    image: e2e
    working_dir: '/workdir'
    volumes:
      - .:/workdir/
      - /workdir/node_modules
    tty: true
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-chrome:3.141.59
    user: root
    shm_size: 2gb
    ports:
      - 4445:4444
      - 9222:9222
